language: python
env:
  global:
    - CI=true

matrix:
  include:
    - os: linux
      python: 3.5
      env: TESTSUITE=lin35 OPENSSL=1.0.1f
      
    - os: linux
      python: 3.5
      env: TESTSUITE=lin35 OPENSSL=1.0.2j
      
    - os: linux
      python: 3.5
      env: TESTSUITE=lin35 OPENSSL=1.1.0c
    
    - os: osx
      sudo: required
      language: generic
      env: TESTSUITE=osx35

#  Manually install python on osx
install: |
  if [ -n "${OPENSSL}" ]; then
      OPENSSL_DIR="ossl-1/${OPENSSL}"
      if [[ ! -f "$HOME/$OPENSSL_DIR/bin/openssl" ]]; then
          curl -O https://www.openssl.org/source/openssl-$OPENSSL.tar.gz
          tar zxf openssl-$OPENSSL.tar.gz
          cd openssl-$OPENSSL
          ./config shared no-asm no-ssl2 no-ssl3 -fPIC --prefix="$HOME/$OPENSSL_DIR"
          # modify the shlib version to a unique one to make sure the dynamic
          # linker doesn't load the system one. This isn't required for 1.1.0 at the
          # moment since our Travis builders have a diff shlib version, but it doesn't hurt
          sed -i "s/^SHLIB_MAJOR=.*/SHLIB_MAJOR=100/" Makefile
          sed -i "s/^SHLIB_MINOR=.*/SHLIB_MINOR=0.0/" Makefile
          sed -i "s/^SHLIB_VERSION_NUMBER=.*/SHLIB_VERSION_NUMBER=100.0.0/" Makefile
          make depend
          make install
          
          # Add new openssl to path
          export PATH="$HOME/$OPENSSL_DIR/bin:$PATH"
          export CFLAGS="-I$HOME/$OPENSSL_DIR/include"
          # rpath on linux will cause it to use an absolute path so we don't need to do LD_LIBRARY_PATH
          export LDFLAGS="-L$HOME/$OPENSSL_DIR/lib -Wl,-rpath=$HOME/$OPENSSL_DIR/lib"
      fi

      cd $TRAVIS_BUILD_DIR
  fi
  
  if [[ $TESTSUITE == 'osx35' ]]; then

      brew update;
      brew outdated openssl || brew upgrade openssl;
      brew install python3;
      python3 -m venv venv;
      source venv/bin/activate;
      # Some openssl infos re: linking
      otool -L $(find .tox -name "_openssl*.so")
  
  fi
  
  pip install . test

script: python tests/trashtest.py

branches:
  only:
    - master